CREATE DATABASE IF NOT EXISTS sapedb;
USE sapedb;

CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(240) NOT NULL,
    gmail VARCHAR(240) NOT NULL,
    password VARCHAR(240) NOT NULL
);