CREATE DATABASE IF NOT EXISTS sapedb;
USE sapedb;
<<<<<<< HEAD
CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(240) NOT NULL,
    email VARCHAR(240) NOT NULL UNIQUE,
    password VARCHAR(240) NOT NULL
);
=======

CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(240) NOT NULL,
    email VARCHAR(240) NOT NULL,
    password VARCHAR(240) NOT NULL
);
>>>>>>> e18d27e601234c2d5bf140e1551208a141c18e78
